spring:
  devtools:
    livereload:
      enabled: true

  datasource:
      driverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: "jdbc:log4jdbc:mariadb://moimdev.cxz28d3n4hpj.ap-northeast-2.rds.amazonaws.com:3306/studyshare"
      username: csj2702
      password: 
  jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true

                     
server:
    port: 8080
    
cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    s3:
      bucket: studyshareimagestorage
    region:
      static: ap-northeast-2
    stack:
      auto: false

      
