spring:
  profiles:
    include:
      - email
  devtools:
    livereload:
      enabled: true

  datasource:
      #driverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      driverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: "jdbc:log4jdbc:mysql://ls-5e1f6dc6cda34ee3ff0a83dddc17e6772c6fe068.cpd3bfmvavpa.ap-northeast-2.rds.amazonaws.com:3306/studyshare?serverTimezone=UTC&characterEncoding=UTF-8"
      username: dbmasteruser
      password: !
  jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 731014591837-ej91nk0hfgf42hfssm12j4uop6ig9hce.apps.googleusercontent.com
            client-secret: DVfYfbX49F_Hz7gzzYuVJrna
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email

                     
server:
    port: 8080
    
cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    s3:
      bucket: studyshareimagestorage
    region:
      static: ap-northeast-2
    stack:
      auto: false

      



